### ISSUE TITLE
Purchase Order SKU

### ISSUE THREAD

**Issue by paris3200** [paris3200/flask-inventory#15]
I believe we need to upgrade the logic for purchase orders.  The purchase order SKU needs to be the SKU that the vendor uses not necessarily the SKU in the app.  It is possible that a single component can be sourced from different vendors all using different SKUs.  

I believe the solution is to separate the ordered items from the components by placing them into a separate database table and tieing them to a vendor.  It might look something like:

### po_items

- id
- sku
- description
- vendor_id

Any thoughts?

**Comment by cisko3000** [comment]
That's a good idea. User would then have to create components manually
after purchase order is processed, of there would have to be a mapping
table? I'm not against it, but probably won't focus on it too much myself
because I want to make more solid tests for tag management and also improve
UI of tags.
   My focus is to create an inventory system where users check items out
and have to eventually return them. And make it easy to use. If the system
can do more than that, then that's cool too I can probably contribute API
or UI stuff to it. I like working with flask-restful.


Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by cisko3000** [comment]
This might be more ambitious but what if there was catalog_item table,
instead of Po_item table? And catalog_item table has foreign key to vendor?
So you can see items for specific vendors.

Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by cisko3000** [comment]
But yeah we should definitely separate components from purchase order.

Francisco Barcena
http://www.LosAngelesCoder.com

**Comment by paris3200** [comment]
I was thinking that eventually there will be a status attached to purchase orders.  Once a purchase order is filled, it would be marked as completed and then a transaction would be automatically added to update components or create components if needed.  

I realize that you're focused on the check-in/check-out system, but it is nice to be able to bounce some ideas off of someone else.  Currently, I'm working on adding line items dynamically.  Once I get that finished up I will work on creating separate components for the purchase orders.

**Comment by cisko3000** [comment]
For sure, sounds good.

**Comment by paris3200** [comment]
Closed by 5131eb9
